name: ASAN

on: [push, pull_request]

jobs:
  linux-gcc-asan:
    name: Linux ASAN
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev  libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          pip install conan

      - name: CMake configure -- Debug
        run: cmake -S. -GNinja -Bcmake-build-asan -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=17 -DMC_BUILD_ASAN=ON -DMC_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-asan

      - name: CTest -- Debug
        run: ctest --test-dir cmake-build-asan -C Debug
