name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        target:
          [
            { "os": "ubuntu-22.04", "cxx": 20 },
            { "os": "ubuntu-22.04", "cxx": 23 },
          ]
      fail-fast: false
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake lcov gcovr

      - name: Install conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Run coverage build
        run: CXX_STD="${{ matrix.target.cxx }}" make coverage-xml

      - uses: codecov/codecov-action@v3
        with:
          files: ./cmake-build-coverage/coverage.xml
          fail_ci_if_error: true
