name: Sanitizers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        std: [17, 20, 23]
        sanitizer:
          [
            { "name": "asan", "flags": "MODERNCIRCUITS_ENABLE_ASAN=ON" },
            { "name": "tsan", "flags": "MODERNCIRCUITS_ENABLE_TSAN=ON" },
            { "name": "ubsan", "flags": "MODERNCIRCUITS_ENABLE_UBSAN=ON" },
          ]
      fail-fast: false
    name: GCC ${{ matrix.sanitizer.name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install conan
        run: |
          pip install conan
          conan profile detect --force
          conan profile show default

      - name: Build dependencies
        run: >
          conan install
          -of build
          --build=missing
          -c tools.cmake.cmaketoolchain:generator=Ninja
          -pr:b=default
          -pr:h=default
          -s compiler.cppstd="${{ matrix.std }}"
          -s build_type=Debug .

      - name: Configure CMake
        run: |
          cmake -S. -B build -G"Ninja" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake" -D CMAKE_CXX_STANDARD="${{ matrix.std }}" -D "${{ matrix.sanitizer.flags }}" -DMODERNCIRCUITS_ENABLE_WERROR=ON

      - name: Show compile commands
        run: cat build/compile_commands.json

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests
        run: ctest --test-dir build -C Debug
