name: Sanitizers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        std: [20, 23]
        sanitizer:
          [
            { "name": "asan", "flags": "MODERNCIRCUITS_ENABLE_ASAN=ON" },
            { "name": "tsan", "flags": "MODERNCIRCUITS_ENABLE_TSAN=ON" },
            { "name": "ubsan", "flags": "MODERNCIRCUITS_ENABLE_UBSAN=ON" },
          ]
      fail-fast: false
    name: GCC ${{ matrix.sanitizer.name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Build dependencies
        run: >
          conan install
          -of build
          --build=missing
          -c tools.cmake.cmaketoolchain:generator=Ninja
          -pr:b=default
          -pr:h=default
          -s compiler.cppstd="${{ matrix.std }}"
          -s build_type=Debug .

      - name: Build
        run: conan build . -of build --build=missing
