name: Clang-Tidy

on: [push, pull_request]

jobs:
  clang-tidy-14:
    name: Clang-Tidy-14
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14 all

      - name: Install Conan
        run: |
          pip install conan
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default
          conan profile update settings.compiler=clang default
          conan profile update settings.compiler.version=14 default
          conan profile update env.CXX=/usr/bin/clang++-14 default
          conan profile update env.CC=/usr/bin/clang-14 default
          conan profile show default

      - name: Build dependencies
        run: |
          conan install -if build --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=14 -s build_type=Release .

      - name: Configure CMake
        run: |
          cmake -S. -B build -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER="clang-14" -D CMAKE_CXX_COMPILER="clang++-14" -D CMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake" -D CMAKE_CXX_STANDARD=14 -D MC_CORE_ENABLE_WERROR=ON

      - name: Clang-Tidy -- Release
        run: >
          BUILD_DIR=build
          PYTHON_BIN=python
          CLANG_REPLACEMENTS_BIN=clang-apply-replacements-14
          CLANG_TIDY_BIN=clang-tidy-14
          make tidy-check
