name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        cxx_std: [14, 17, 20]
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake lcov gcovr

      - name: Install conan
        run: |
          pip install conan
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: Run coverage build
        run: CXX_STD="${{ matrix.cxx_std }}" make coverage-xml

      - uses: codecov/codecov-action@v3
        with:
          files: ./cmake-build-coverage/coverage.xml
          fail_ci_if_error: true
