name: Linux

on: [push, pull_request]

jobs:
  gcc:
    name: GCC
    strategy:
      matrix:
        gcc_version: [10, 11]
        cxx_std: [14, 17, 20]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: "${{ matrix.gcc_version }}"
          platform: x64

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          pip install conan
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: |
          mkdir build
          cd build
          conan install --build=missing -pr:b=default -pr:h=default -s compiler.cppstd="${{ matrix.cxx_std }}" -s build_type=Release ..
          conan build ..
