name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build & Test
    strategy:
      matrix:
        target:
          [
            { "osx": "10.11", "cxx": 14 },
            { "osx": "10.14", "cxx": 17 },
            { "osx": "11.0", "cxx": 20 },
          ]
      fail-fast: false
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.target.osx }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: brew install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: Build dependencies - Debug
        run: >
          conan install
          -if build
          --build=missing
          -pr:b=default
          -pr:h=default
          -c user.build:all=True
          -s compiler.cppstd="${{ matrix.target.cxx }}"
          -s build_type=Debug .

      - name: Build dependencies - Release
        run: >
          conan install
          -if build
          --build=missing
          -pr:b=default
          -pr:h=default
          -c user.build:all=True
          -s compiler.cppstd="${{ matrix.target.cxx }}"
          -s build_type=Release .

      - name: Build
        run: >
          cmake -S . -B build
          -G "Ninja Multi-Config"
          -D CMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake"
          -D CMAKE_CXX_STANDARD="${{ matrix.target.cxx }}"
          -D MODERNCIRCUITS_ENABLE_WERROR=ON

      - name: Build dependencies - Debug
        run: cmake --build build --config Debug

      - name: Build dependencies - Release
        run: cmake --build build --config Release

      - name: Test - Debug
        run: ctest --test-dir build -C Debug --output-on-failure

      - name: Test - Release
        run: ctest --test-dir build -C Release --output-on-failure
