name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gcc:
    name: GCC
    strategy:
      matrix:
        cxx_std: [20, 23]
        build_type: ["Debug", "Release"]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake

      - name: Install conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Build Dependencies
        run: >
          conan install
          -of build
          --build=missing
          -pr:b=default
          -pr:h=default
          -c tools.cmake.cmaketoolchain:generator=Ninja
          -s compiler.cppstd="${{ matrix.cxx_std }}"
          -s build_type="${{ matrix.build_type }}" .

      - name: Build & Test
        run: conan build . -of build --build=missing
