name: Linux

on: [push, pull_request]

jobs:
  gcc9:
    name: GCC-9 C++17
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          pip install conan
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: |
          cd build
          conan install --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=17 -s build_type=Release ..
          conan build ..

  gcc10:
    name: GCC-10 C++20
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 10
          platform: x64

      - name: Install dependencies
        run: |
          sudo apt install -y ninja-build libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
          pip install conan
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: |
          cd build
          conan install --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=20 -s build_type=Release ..
          conan build ..
