name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build & Test
    strategy:
      matrix:
        osx_target: ["10.11", "10.14", "11.0"]
        cxx_std: [14, 17, 20]
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.osx_target }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install ninja
        run: brew install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan config init
          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

      - name: CMake configure -- Release
        run: |
          mkdir build
          cd build
          conan install --build=missing -pr:b=default -pr:h=default -s compiler.cppstd="${{ matrix.cxx_std }}" -s build_type=Release ..
          conan build ..
