name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    name: Build & Test
    strategy:
      matrix:
        build_type: ["Debug", "Release"]
        target:
          [
            { "runner": "macos-10.15", "target": "10.14", "cxx": 17 },
            { "runner": "macos-11", "target": "11.0", "cxx": 20 },
          ]
      fail-fast: false
    runs-on: ${{ matrix.target.runner }}
    env:
      MACOSX_DEPLOYMENT_TARGET: "${{ matrix.target.target }}"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install ninja
        run: brew install ninja

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan profile detect --force

      - name: Build Dependencies
        run: >
          conan install
          -of build
          --build=missing
          -pr:b=default
          -pr:h=default
          -c tools.cmake.cmaketoolchain:generator=Ninja
          -s compiler.cppstd="${{ matrix.target.cxx }}"
          -s build_type="${{ matrix.build_type }}" .

      - name: Build & Test
        run: conan build . -of build --build=missing
