name: FreeBSD

on: [push, pull_request]

jobs:
  freebsd:
    name: FreeBSD
    runs-on: macos-12
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test on FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y cmake ninja
            pip install conan

          run: |
            pwd
            ls -lah
            freebsd-version

            conan config init
            conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default

            conan install -if build --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=17 -s build_type=Debug .
            conan install -if build --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=17 -s build_type=Release .

            cmake -S. -Bbuild -G"Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake" -DCMAKE_CXX_STANDARD=17 -DMC_CORE_ENABLE_WERROR=ON
            cmake --build build --config Debug
            cmake --build build --config Release

            ctest --test-dir build -C Debug --output-on-failure
            ctest --test-dir build -C Release --output-on-failure
