name: FreeBSD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  freebsd:
    name: FreeBSD
    runs-on: macos-12
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test on FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y cmake conan

          run: |
            pwd
            ls -lah
            freebsd-version

            conan config init
            conan install -if build --build=missing -pr:b=default -pr:h=default -s compiler.cppstd=17 -s build_type=Release .

            cmake -S. -B build -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE="build/conan_toolchain.cmake" -D CMAKE_CXX_STANDARD=17 -DMC_CORE_ENABLE_WERROR=ON
            cmake --build build
            ctest --test-dir build -C Release --output-on-failure
